### ISSUE TITLE
Server to-do

### ISSUE THREAD

**Issue by fernandobrito** [GustavoKatel/computerNetworksAssignment#1]
- [x] [GUI] Ask coordinator IP at startup
- [x] Implement SERVER ADD (send to coordinator)
- [x] Notify coordinator of active channels every X seconds
- [ ] Notify all users of user disconnection
- [ ] Notify all users of users list every X seconds
